* configure script extended (but still need work ;-)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,25 +1,184 @@
-#!/bin/bash
+#! /bin/bash
 # $Id$
 
-INCLUDE=${1:-"$PWD/include"}
+### Default Values
+# (change here or use configure option interface (the clean way))
 
-echo "/* Generated config.h */" >config.h
+prefix=/usr
 
-echo "checking for alloca..."
-cat >/tmp/allocatest.c <<EOF
+
+# compiler flags
+
+WARNINGS="-Wall -W -Wwrite-strings -Wsign-compare \
+-Wpointer-arith -Wcast-qual -Wcast-align \
+-Wstrict-prototypes -Wmissing-prototypes \
+-Wnested-externs -Winline -Wshadow -Wformat=2"
+ 
+
+
+
+
+
+
+### Stop Editing Here  (expect you know what you are doing)
+
+# Developer Notes:
+#
+# o Take a look at the end of this file of this configure-script
+#   for the script execution order
+# 
+# o If you add an test-case note the order (e.g. check_for_alloca)
+#   1. STDOUT output
+#   2. config.h output
+#
+# o Script improvements, hints or anything else is welcome!
+#   send email to the netsend developers
+#   (http://netsend.berlios.de/deve.html)
+
+
+# internal configure values
+
+c_red="\033[31,1m"
+c_reset="\033[0m"
+
+
+# function declarations
+
+usage()
+{
+  cat << EOF
+  Usage: configure [options]
+  Options: [defaults in brackets after descriptions]
+  Configuration:
+    --help                  print this message
+    --prefix=PREFIX         install architecture-independent files in PREFIX (/usr)
+    --enable-debug          enable debug information (#define DEBUG and add CFLAGS -g)
+    --verbose               enable verbose configure output (hacker-mode[tm])
+EOF
+}
+
+parse_args()
+{
+	ac_prev=
+
+	for ac_option
+	do
+		if test -n "$ac_prev"; then
+			eval "$ac_prev=\$ac_option"
+			ac_prev=
+			continue
+		fi
+
+		case "$ac_option" in
+			-*=*) ac_optarg=`echo "$ac_option" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
+			*) ac_optarg= ;;
+		esac
+
+		case "$ac_option" in
+
+			--enable-debug | -enable-debug)
+			debug="yes"
+			;;
+
+			-help | --help | -h)
+			usage;
+			exit 0;
+			;;
+
+			-prefix | --prefix | --prefi | --pref | --pre | --pr | --p)
+			ac_prev=prefix
+			;;
+			-prefix=* | --prefix=* | --prefi=* | --pref=* | --pre=* | --pr=* | --p=*)
+			prefix="$ac_optarg"
+			;;
+
+			-*) { echo "configure: error: $ac_option: invalid option; use --help to show usage" 1>&2; exit 1; }
+			;;
+
+			*)
+			;;
+
+		esac
+	done
+}
+
+print_config_header()
+{
+	# stdout stuff
+	echo "*** configure-ng ***"
+
+	# Make.Rules stuff
+	echo -e "# Make.Rules.  Generated by configure script\n"  > Make.Rules
+
+	# config.h stuff
+	echo -n "/* Generated config.h see configure script for"  > config.h
+	echo    " further information */"                        >> config.h
+}
+
+create_make_rules()
+{
+	echo "prefix =  $prefix"             >> Make.Rules
+	echo "exec_prefix = \${prefix}"      >> Make.Rules
+	echo
+	echo  "bindir = \${exec_prefix}/bin" >> Make.Rules
+	
+	# compiler flags
+	if [ "$debug" = yes ] ; then
+		echo "DEBUG=-g -O0 -DDEBUG"          >> Make.Rules
+	fi
+	echo "WARNINGS = $WARNINGS"            >> Make.Rules
+	echo "CFLAGS = \$(WARNINGS) \$(DEBUG)" >> Make.Rules
+}
+
+
+
+check_for_alloca()
+{
+	echo -n "checking for alloca..."
+
+	cat > /tmp/allocatest.c <<EOF
 #include <alloca.h>
 int main(int argc, char **argv){
-    alloca(23);
-    return 0;
+alloca(23);
+return 0;
 }
 EOF
-gcc -I$INCLUDE -o /tmp/allocatest /tmp/allocatest.c >/dev/null 2>&1
-if [ $? -eq 0 ]
-then
-    echo "#define HAVE_ALLOCA 1" >>config.h
-else
-    echo "#undef HAVE_ALLOCA" >>config.h
+  gcc -o /tmp/allocatest /tmp/allocatest.c >/dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		echo " yes"
+		echo "#define HAVE_ALLOCA 1" >>config.h
+	else
+		echo " no"
+		echo "#undef HAVE_ALLOCA" >>config.h
 
-fi
-rm -f /tmp/allocatest /tmp/allocatest.c
+	fi
+	rm -f /tmp/allocatest /tmp/allocatest.c
+}
 
+print_config()
+{
+	echo -e "Wow! Your environemt looks quite nice - fine!"
+	echo -e "\nConfigure picked following defaults, options and paths:"
+	echo -e "Please validate this values (at least it isn't my box ;-)"
+	echo
+	echo "  Prefix: $prefix"
+	if [ "$debug" = yes ] ; then
+		echo "  Debug:  yes"
+	else
+		echo "  Debug:  no"
+	fi
+	echo
+}
+
+
+parse_args $*
+print_config_header
+create_make_rules
+
+check_for_alloca
+
+print_config
+
+
+# vim:set ts=2 sw=2 tw=78 noet:
